import type { Metadata } from "next";
// import { Geist, Geist_Mono, Rubik, Noto_Sans } from "next/font/google";
import { aeonik } from "./fonts";
import "./globals.css";
import { ReduxProvider } from "@/providers";

// const noto = Noto_Sans({
//   variable: "--font-noto-sans",
//   subsets: ["latin", "cyrillic"],
// });

// const rubik = Rubik({
//   variable: "--font-rubik",
//   subsets: [
//     "arabic",
//     "cyrillic",
//     "cyrillic-ext",
//     "hebrew",
//     "latin",
//     "latin-ext",
//   ],
// });

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className={`${aeonik.className} bg-[#151619] antialiased`}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
